import { DEFAULT_LOCALE, Locale } from "@/data/i18n/types";
import { isValidLocale } from "@/data/i18n/locales";

/**
 * Small UI-chrome strings (aria labels, form validation, plan-type labels…)
 * that are not part of the SEO dictionaries. Kept separate so SEO copy in
 * `data/i18n/*` stays untouched.
 */
export interface UiText {
  skip: string;
  mainNav: string;
  openMenu: string;
  closeMenu: string;
  selectLanguage: string;
  languageHeading: string;
  languages: string;
  close: string;
  breadcrumb: string;
  // plan types
  planClients: string;
  planResellers: string;
  planTypeLabel: string;
  clientsHint: string;
  resellersHint: string;
  oneTimePayment: string;
  perMonth: string;
  perCredit: string;
  credits: string;
  orderReseller: string;
  resellerPlansBadge: string;
  resellerPlansTitle: string;
  resellerPlansSubtitle: string;
  seeResellerPlans: string;
  // forms
  required: string;
  fieldRequired: string;
  fieldEmail: string;
  fieldPhone: string;
  networkError: string;
  genericError: string;
  trialWhatsappFallback: string;
  namePlaceholder: string;
  recommended: string;
  other: string;
  // 404
  notFoundTitle: string;
  notFoundText: string;
  goHome: string;
  orderWhatsapp: string;
  orderMessage: string;
}

const de: UiText = {
  skip: "Zum Inhalt springen",
  mainNav: "Hauptnavigation",
  openMenu: "Menü öffnen",
  closeMenu: "Menü schließen",
  selectLanguage: "Sprache auswählen",
  languageHeading: "Sprache wählen",
  languages: "Sprachen",
  close: "Schließen",
  breadcrumb: "Brotkrumen-Navigation",
  planClients: "Für Kunden",
  planResellers: "Für Reseller",
  planTypeLabel: "Tarifart wählen",
  clientsHint: "Abos zum Fernsehen – für Privatkunden",
  resellersHint: "Credit-Pakete zum Weiterverkauf (B2B)",
  oneTimePayment: "Einmalzahlung",
  perMonth: "/ Monat",
  perCredit: "/ Credit",
  credits: "Credits",
  orderReseller: "Reseller-Paket anfragen",
  resellerPlansBadge: "B2B Großhandels-Preise",
  resellerPlansTitle: "Reseller Credit-Pakete",
  resellerPlansSubtitle:
    "Je größer das Paket, desto günstiger der Credit-Preis. Credits verfallen nie. Diese Pakete richten sich an Wiederverkäufer – keine Endkunden-Abos.",
  seeResellerPlans: "Reseller-Pakete ansehen",
  required: "Pflichtfeld",
  fieldRequired: "Bitte füllen Sie dieses Feld aus.",
  fieldEmail: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
  fieldPhone: "Bitte geben Sie eine gültige Nummer mit Landesvorwahl ein.",
  networkError: "Netzwerkfehler. Bitte versuchen Sie es erneut oder schreiben Sie uns per WhatsApp.",
  genericError: "Die Anfrage konnte nicht gesendet werden. Bitte schreiben Sie uns per WhatsApp.",
  trialWhatsappFallback: "Lieber direkt per WhatsApp anfragen",
  namePlaceholder: "Max Mustermann",
  recommended: "empfohlen",
  other: "Sonstige",
  notFoundTitle: "Seite nicht gefunden",
  notFoundText: "Die gesuchte Seite existiert nicht oder wurde verschoben.",
  goHome: "Zur Startseite",
  orderWhatsapp: "Per WhatsApp bestellen",
  orderMessage: "Ich möchte folgendes Paket bestellen",
};

const en: UiText = {
  skip: "Skip to content",
  mainNav: "Main navigation",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  selectLanguage: "Select language",
  languageHeading: "Choose language",
  languages: "languages",
  close: "Close",
  breadcrumb: "Breadcrumb",
  planClients: "For customers",
  planResellers: "For resellers",
  planTypeLabel: "Choose plan type",
  clientsHint: "Viewing subscriptions for private customers",
  resellersHint: "Credit packages for resale (B2B)",
  oneTimePayment: "One-time payment",
  perMonth: "/ month",
  perCredit: "/ credit",
  credits: "credits",
  orderReseller: "Request reseller package",
  resellerPlansBadge: "B2B wholesale pricing",
  resellerPlansTitle: "Reseller credit packages",
  resellerPlansSubtitle:
    "The bigger the package, the lower the price per credit. Credits never expire. These packages are for resellers – not end-customer subscriptions.",
  seeResellerPlans: "View reseller packages",
  required: "Required",
  fieldRequired: "Please fill in this field.",
  fieldEmail: "Please enter a valid email address.",
  fieldPhone: "Please enter a valid number including country code.",
  networkError: "Network error. Please try again or contact us via WhatsApp.",
  genericError: "Your request could not be sent. Please contact us via WhatsApp.",
  trialWhatsappFallback: "Prefer to request directly on WhatsApp",
  namePlaceholder: "John Smith",
  recommended: "recommended",
  other: "Other",
  notFoundTitle: "Page not found",
  notFoundText: "The page you are looking for does not exist or has been moved.",
  goHome: "Back to home",
  orderWhatsapp: "Order via WhatsApp",
  orderMessage: "I would like to order this plan",
};

const fr: UiText = {
  skip: "Aller au contenu",
  mainNav: "Navigation principale",
  openMenu: "Ouvrir le menu",
  closeMenu: "Fermer le menu",
  selectLanguage: "Choisir la langue",
  languageHeading: "Choisir la langue",
  languages: "langues",
  close: "Fermer",
  breadcrumb: "Fil d'Ariane",
  planClients: "Pour les clients",
  planResellers: "Pour les revendeurs",
  planTypeLabel: "Choisir le type d'offre",
  clientsHint: "Abonnements TV pour particuliers",
  resellersHint: "Packs de crédits à revendre (B2B)",
  oneTimePayment: "Paiement unique",
  perMonth: "/ mois",
  perCredit: "/ crédit",
  credits: "crédits",
  orderReseller: "Demander le pack revendeur",
  resellerPlansBadge: "Tarifs de gros B2B",
  resellerPlansTitle: "Packs de crédits revendeur",
  resellerPlansSubtitle:
    "Plus le pack est grand, plus le prix par crédit baisse. Les crédits n'expirent jamais. Ces packs s'adressent aux revendeurs – pas aux abonnements clients.",
  seeResellerPlans: "Voir les packs revendeur",
  required: "Obligatoire",
  fieldRequired: "Veuillez remplir ce champ.",
  fieldEmail: "Veuillez saisir une adresse e-mail valide.",
  fieldPhone: "Veuillez saisir un numéro valide avec indicatif pays.",
  networkError: "Erreur réseau. Réessayez ou contactez-nous via WhatsApp.",
  genericError: "Votre demande n'a pas pu être envoyée. Contactez-nous via WhatsApp.",
  trialWhatsappFallback: "Préférez demander directement sur WhatsApp",
  namePlaceholder: "Jean Dupont",
  recommended: "recommandé",
  other: "Autre",
  notFoundTitle: "Page introuvable",
  notFoundText: "La page demandée n'existe pas ou a été déplacée.",
  goHome: "Retour à l'accueil",
  orderWhatsapp: "Commander via WhatsApp",
  orderMessage: "Je souhaite commander cette offre",
};

const es: UiText = {
  skip: "Saltar al contenido",
  mainNav: "Navegación principal",
  openMenu: "Abrir menú",
  closeMenu: "Cerrar menú",
  selectLanguage: "Seleccionar idioma",
  languageHeading: "Elegir idioma",
  languages: "idiomas",
  close: "Cerrar",
  breadcrumb: "Migas de pan",
  planClients: "Para clientes",
  planResellers: "Para revendedores",
  planTypeLabel: "Elegir tipo de plan",
  clientsHint: "Suscripciones de TV para particulares",
  resellersHint: "Paquetes de créditos para reventa (B2B)",
  oneTimePayment: "Pago único",
  perMonth: "/ mes",
  perCredit: "/ crédito",
  credits: "créditos",
  orderReseller: "Solicitar paquete de revendedor",
  resellerPlansBadge: "Precios mayoristas B2B",
  resellerPlansTitle: "Paquetes de créditos para revendedores",
  resellerPlansSubtitle:
    "Cuanto mayor el paquete, menor el precio por crédito. Los créditos nunca caducan. Estos paquetes son para revendedores, no para suscripciones de clientes.",
  seeResellerPlans: "Ver paquetes de revendedor",
  required: "Obligatorio",
  fieldRequired: "Por favor, rellene este campo.",
  fieldEmail: "Introduzca una dirección de correo válida.",
  fieldPhone: "Introduzca un número válido con prefijo internacional.",
  networkError: "Error de red. Inténtelo de nuevo o contáctenos por WhatsApp.",
  genericError: "No se pudo enviar su solicitud. Contáctenos por WhatsApp.",
  trialWhatsappFallback: "Prefiero solicitarlo directamente por WhatsApp",
  namePlaceholder: "Juan Pérez",
  recommended: "recomendado",
  other: "Otro",
  notFoundTitle: "Página no encontrada",
  notFoundText: "La página que busca no existe o se ha movido.",
  goHome: "Volver al inicio",
  orderWhatsapp: "Pedir por WhatsApp",
  orderMessage: "Quiero pedir este plan",
};

const it: UiText = {
  skip: "Vai al contenuto",
  mainNav: "Navigazione principale",
  openMenu: "Apri menu",
  closeMenu: "Chiudi menu",
  selectLanguage: "Seleziona la lingua",
  languageHeading: "Scegli la lingua",
  languages: "lingue",
  close: "Chiudi",
  breadcrumb: "Percorso di navigazione",
  planClients: "Per i clienti",
  planResellers: "Per i rivenditori",
  planTypeLabel: "Scegli il tipo di piano",
  clientsHint: "Abbonamenti TV per privati",
  resellersHint: "Pacchetti di crediti da rivendere (B2B)",
  oneTimePayment: "Pagamento unico",
  perMonth: "/ mese",
  perCredit: "/ credito",
  credits: "crediti",
  orderReseller: "Richiedi il pacchetto rivenditore",
  resellerPlansBadge: "Prezzi all'ingrosso B2B",
  resellerPlansTitle: "Pacchetti crediti per rivenditori",
  resellerPlansSubtitle:
    "Più grande è il pacchetto, più basso è il prezzo per credito. I crediti non scadono mai. Questi pacchetti sono per i rivenditori, non per gli abbonamenti dei clienti.",
  seeResellerPlans: "Vedi i pacchetti rivenditore",
  required: "Obbligatorio",
  fieldRequired: "Compila questo campo.",
  fieldEmail: "Inserisci un indirizzo e-mail valido.",
  fieldPhone: "Inserisci un numero valido con prefisso internazionale.",
  networkError: "Errore di rete. Riprova o contattaci su WhatsApp.",
  genericError: "Impossibile inviare la richiesta. Contattaci su WhatsApp.",
  trialWhatsappFallback: "Preferisci richiederlo direttamente su WhatsApp",
  namePlaceholder: "Mario Rossi",
  recommended: "consigliato",
  other: "Altro",
  notFoundTitle: "Pagina non trovata",
  notFoundText: "La pagina cercata non esiste o è stata spostata.",
  goHome: "Torna alla home",
  orderWhatsapp: "Ordina su WhatsApp",
  orderMessage: "Vorrei ordinare questo piano",
};

const pt: UiText = {
  skip: "Saltar para o conteúdo",
  mainNav: "Navegação principal",
  openMenu: "Abrir menu",
  closeMenu: "Fechar menu",
  selectLanguage: "Selecionar idioma",
  languageHeading: "Escolher idioma",
  languages: "idiomas",
  close: "Fechar",
  breadcrumb: "Caminho de navegação",
  planClients: "Para clientes",
  planResellers: "Para revendedores",
  planTypeLabel: "Escolher tipo de plano",
  clientsHint: "Subscrições de TV para particulares",
  resellersHint: "Pacotes de créditos para revenda (B2B)",
  oneTimePayment: "Pagamento único",
  perMonth: "/ mês",
  perCredit: "/ crédito",
  credits: "créditos",
  orderReseller: "Pedir pacote de revendedor",
  resellerPlansBadge: "Preços grossistas B2B",
  resellerPlansTitle: "Pacotes de créditos para revendedores",
  resellerPlansSubtitle:
    "Quanto maior o pacote, menor o preço por crédito. Os créditos nunca expiram. Estes pacotes destinam-se a revendedores, não a subscrições de clientes.",
  seeResellerPlans: "Ver pacotes de revendedor",
  required: "Obrigatório",
  fieldRequired: "Preencha este campo.",
  fieldEmail: "Introduza um endereço de e-mail válido.",
  fieldPhone: "Introduza um número válido com indicativo do país.",
  networkError: "Erro de rede. Tente novamente ou contacte-nos pelo WhatsApp.",
  genericError: "Não foi possível enviar o pedido. Contacte-nos pelo WhatsApp.",
  trialWhatsappFallback: "Prefere pedir diretamente pelo WhatsApp",
  namePlaceholder: "João Silva",
  recommended: "recomendado",
  other: "Outro",
  notFoundTitle: "Página não encontrada",
  notFoundText: "A página procurada não existe ou foi movida.",
  goHome: "Voltar ao início",
  orderWhatsapp: "Encomendar pelo WhatsApp",
  orderMessage: "Quero encomendar este plano",
};

const nl: UiText = {
  skip: "Ga naar de inhoud",
  mainNav: "Hoofdnavigatie",
  openMenu: "Menu openen",
  closeMenu: "Menu sluiten",
  selectLanguage: "Taal kiezen",
  languageHeading: "Kies een taal",
  languages: "talen",
  close: "Sluiten",
  breadcrumb: "Kruimelpad",
  planClients: "Voor klanten",
  planResellers: "Voor resellers",
  planTypeLabel: "Kies het type abonnement",
  clientsHint: "Tv-abonnementen voor particulieren",
  resellersHint: "Creditpakketten voor wederverkoop (B2B)",
  oneTimePayment: "Eenmalige betaling",
  perMonth: "/ maand",
  perCredit: "/ credit",
  credits: "credits",
  orderReseller: "Resellerpakket aanvragen",
  resellerPlansBadge: "B2B groothandelsprijzen",
  resellerPlansTitle: "Reseller creditpakketten",
  resellerPlansSubtitle:
    "Hoe groter het pakket, hoe lager de prijs per credit. Credits vervallen nooit. Deze pakketten zijn voor resellers, niet voor klantabonnementen.",
  seeResellerPlans: "Bekijk resellerpakketten",
  required: "Verplicht",
  fieldRequired: "Vul dit veld in.",
  fieldEmail: "Voer een geldig e-mailadres in.",
  fieldPhone: "Voer een geldig nummer met landcode in.",
  networkError: "Netwerkfout. Probeer het opnieuw of neem contact op via WhatsApp.",
  genericError: "Uw aanvraag kon niet worden verzonden. Neem contact op via WhatsApp.",
  trialWhatsappFallback: "Liever direct via WhatsApp aanvragen",
  namePlaceholder: "Jan de Vries",
  recommended: "aanbevolen",
  other: "Overig",
  notFoundTitle: "Pagina niet gevonden",
  notFoundText: "De gezochte pagina bestaat niet of is verplaatst.",
  goHome: "Terug naar home",
  orderWhatsapp: "Bestellen via WhatsApp",
  orderMessage: "Ik wil dit abonnement bestellen",
};

const pl: UiText = {
  skip: "Przejdź do treści",
  mainNav: "Nawigacja główna",
  openMenu: "Otwórz menu",
  closeMenu: "Zamknij menu",
  selectLanguage: "Wybierz język",
  languageHeading: "Wybierz język",
  languages: "języków",
  close: "Zamknij",
  breadcrumb: "Ścieżka nawigacji",
  planClients: "Dla klientów",
  planResellers: "Dla resellerów",
  planTypeLabel: "Wybierz rodzaj planu",
  clientsHint: "Abonamenty TV dla klientów indywidualnych",
  resellersHint: "Pakiety kredytów do odsprzedaży (B2B)",
  oneTimePayment: "Płatność jednorazowa",
  perMonth: "/ miesiąc",
  perCredit: "/ kredyt",
  credits: "kredytów",
  orderReseller: "Zapytaj o pakiet resellera",
  resellerPlansBadge: "Ceny hurtowe B2B",
  resellerPlansTitle: "Pakiety kredytów dla resellerów",
  resellerPlansSubtitle:
    "Im większy pakiet, tym niższa cena kredytu. Kredyty nigdy nie wygasają. Pakiety są przeznaczone dla resellerów, a nie dla abonamentów klientów.",
  seeResellerPlans: "Zobacz pakiety resellera",
  required: "Wymagane",
  fieldRequired: "Wypełnij to pole.",
  fieldEmail: "Podaj poprawny adres e-mail.",
  fieldPhone: "Podaj poprawny numer z numerem kierunkowym kraju.",
  networkError: "Błąd sieci. Spróbuj ponownie lub napisz do nas na WhatsApp.",
  genericError: "Nie udało się wysłać zgłoszenia. Napisz do nas na WhatsApp.",
  trialWhatsappFallback: "Wolę poprosić bezpośrednio przez WhatsApp",
  namePlaceholder: "Jan Kowalski",
  recommended: "polecane",
  other: "Inne",
  notFoundTitle: "Nie znaleziono strony",
  notFoundText: "Strona, której szukasz, nie istnieje lub została przeniesiona.",
  goHome: "Wróć na stronę główną",
  orderWhatsapp: "Zamów przez WhatsApp",
  orderMessage: "Chcę zamówić ten plan",
};

const tr: UiText = {
  skip: "İçeriğe geç",
  mainNav: "Ana gezinme",
  openMenu: "Menüyü aç",
  closeMenu: "Menüyü kapat",
  selectLanguage: "Dil seçin",
  languageHeading: "Dil seçin",
  languages: "dil",
  close: "Kapat",
  breadcrumb: "Sayfa yolu",
  planClients: "Müşteriler için",
  planResellers: "Bayiler için",
  planTypeLabel: "Paket türünü seçin",
  clientsHint: "Bireysel müşteriler için TV abonelikleri",
  resellersHint: "Yeniden satış için kredi paketleri (B2B)",
  oneTimePayment: "Tek seferlik ödeme",
  perMonth: "/ ay",
  perCredit: "/ kredi",
  credits: "kredi",
  orderReseller: "Bayi paketi talep et",
  resellerPlansBadge: "B2B toptan fiyatlar",
  resellerPlansTitle: "Bayi kredi paketleri",
  resellerPlansSubtitle:
    "Paket büyüdükçe kredi fiyatı düşer. Krediler asla sona ermez. Bu paketler bayiler içindir, son kullanıcı abonelikleri değildir.",
  seeResellerPlans: "Bayi paketlerini gör",
  required: "Zorunlu",
  fieldRequired: "Lütfen bu alanı doldurun.",
  fieldEmail: "Lütfen geçerli bir e-posta adresi girin.",
  fieldPhone: "Lütfen ülke koduyla birlikte geçerli bir numara girin.",
  networkError: "Ağ hatası. Lütfen tekrar deneyin veya WhatsApp'tan bize ulaşın.",
  genericError: "Talebiniz gönderilemedi. Lütfen WhatsApp'tan bize ulaşın.",
  trialWhatsappFallback: "Doğrudan WhatsApp'tan talep etmeyi tercih ederim",
  namePlaceholder: "Ahmet Yılmaz",
  recommended: "önerilen",
  other: "Diğer",
  notFoundTitle: "Sayfa bulunamadı",
  notFoundText: "Aradığınız sayfa mevcut değil veya taşınmış.",
  goHome: "Ana sayfaya dön",
  orderWhatsapp: "WhatsApp ile sipariş ver",
  orderMessage: "Bu paketi sipariş etmek istiyorum",
};

const sq: UiText = {
  skip: "Kalo te përmbajtja",
  mainNav: "Navigimi kryesor",
  openMenu: "Hap menunë",
  closeMenu: "Mbyll menunë",
  selectLanguage: "Zgjidh gjuhën",
  languageHeading: "Zgjidh gjuhën",
  languages: "gjuhë",
  close: "Mbyll",
  breadcrumb: "Shtegu i navigimit",
  planClients: "Për klientët",
  planResellers: "Për rishitësit",
  planTypeLabel: "Zgjidh llojin e planit",
  clientsHint: "Abonime TV për klientë privatë",
  resellersHint: "Paketa kreditesh për rishitje (B2B)",
  oneTimePayment: "Pagesë e vetme",
  perMonth: "/ muaj",
  perCredit: "/ kredit",
  credits: "kredite",
  orderReseller: "Kërko paketën e rishitësit",
  resellerPlansBadge: "Çmime shumice B2B",
  resellerPlansTitle: "Paketa kreditesh për rishitës",
  resellerPlansSubtitle:
    "Sa më e madhe paketa, aq më i ulët çmimi për kredit. Kreditet nuk skadojnë kurrë. Këto paketa janë për rishitës, jo për abonime klientësh.",
  seeResellerPlans: "Shiko paketat e rishitësit",
  required: "I detyrueshëm",
  fieldRequired: "Ju lutem plotësoni këtë fushë.",
  fieldEmail: "Ju lutem shkruani një adresë e-mail të vlefshme.",
  fieldPhone: "Ju lutem shkruani një numër të vlefshëm me kodin e shtetit.",
  networkError: "Gabim rrjeti. Provoni përsëri ose na shkruani në WhatsApp.",
  genericError: "Kërkesa nuk u dërgua. Na shkruani në WhatsApp.",
  trialWhatsappFallback: "Preferoj ta kërkoj direkt në WhatsApp",
  namePlaceholder: "Arben Hoxha",
  recommended: "i rekomanduar",
  other: "Tjetër",
  notFoundTitle: "Faqja nuk u gjet",
  notFoundText: "Faqja që kërkoni nuk ekziston ose është zhvendosur.",
  goHome: "Kthehu në faqen kryesore",
  orderWhatsapp: "Porosit në WhatsApp",
  orderMessage: "Dua të porosis këtë paketë",
};

const ar: UiText = {
  skip: "انتقل إلى المحتوى",
  mainNav: "التنقل الرئيسي",
  openMenu: "فتح القائمة",
  closeMenu: "إغلاق القائمة",
  selectLanguage: "اختر اللغة",
  languageHeading: "اختر اللغة",
  languages: "لغة",
  close: "إغلاق",
  breadcrumb: "مسار التنقل",
  planClients: "للعملاء",
  planResellers: "للموزعين",
  planTypeLabel: "اختر نوع الباقة",
  clientsHint: "اشتراكات المشاهدة للأفراد",
  resellersHint: "باقات رصيد لإعادة البيع (B2B)",
  oneTimePayment: "دفعة واحدة",
  perMonth: "/ شهر",
  perCredit: "/ رصيد",
  credits: "رصيد",
  orderReseller: "اطلب باقة الموزع",
  resellerPlansBadge: "أسعار الجملة B2B",
  resellerPlansTitle: "باقات رصيد الموزعين",
  resellerPlansSubtitle:
    "كلما كبرت الباقة انخفض سعر الرصيد. الرصيد لا تنتهي صلاحيته أبداً. هذه الباقات مخصصة للموزعين وليست اشتراكات للعملاء.",
  seeResellerPlans: "عرض باقات الموزعين",
  required: "مطلوب",
  fieldRequired: "يرجى ملء هذا الحقل.",
  fieldEmail: "يرجى إدخال بريد إلكتروني صالح.",
  fieldPhone: "يرجى إدخال رقم صالح مع رمز الدولة.",
  networkError: "خطأ في الشبكة. حاول مرة أخرى أو تواصل معنا عبر واتساب.",
  genericError: "تعذر إرسال طلبك. يرجى التواصل معنا عبر واتساب.",
  trialWhatsappFallback: "أفضّل الطلب مباشرة عبر واتساب",
  namePlaceholder: "محمد أحمد",
  recommended: "موصى به",
  other: "أخرى",
  notFoundTitle: "الصفحة غير موجودة",
  notFoundText: "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",
  goHome: "العودة إلى الرئيسية",
  orderWhatsapp: "اطلب عبر واتساب",
  orderMessage: "أرغب في طلب هذه الباقة",
};

const texts: Record<Locale, UiText> = { de, en, fr, es, it, pt, nl, pl, tr, sq, ar };

export function getUiText(locale: string = DEFAULT_LOCALE): UiText {
  return isValidLocale(locale) ? texts[locale] : texts[DEFAULT_LOCALE];
}
